apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: authdb
spec:
  ports:
    - port: 5432
  selector:
    app: authdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - name: authdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "auth"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authdb-data
      volumes:
        - name: authdb-data
          persistentVolumeClaim:
            claimName: authdb-pvc