apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: backend-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE_SERVICE_URL
              value: "http://message:8080"
            - name: POST_SERVICE_URL
              value: "http://post:8080"
            - name: USER_SERVICE_URL
              value: "http://user:8080"
            - name: NOTI_SERVICE_URL
              value: "http://noti:8080"