apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notidb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: notidb
spec:
  ports:
    - port: 5432
  selector:
    app: notidb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notidb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notidb
  template:
    metadata:
      labels:
        app: notidb
    spec:
      containers:
        - name: notidb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "noti"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data 
              name: notidb-data
      volumes:
        - name: notidb-data
          persistentVolumeClaim:
            claimName: notidb-pvc