apiVersion: v1
kind: Service
metadata: 
  name: noti
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: noti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noti
  template:
    metadata:
      labels:
        app: noti
    spec:
      containers:
        - name: noti
          image: backend-noti:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 