apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postdb
spec:
  ports:
    - port: 27017
  selector:
    app: postdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postdb
  template:
    metadata:
      labels:
        app: postdb
    spec:
      containers:
        - name: postdb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin123"
          volumeMounts:
            - mountPath: /data/db
              name: postdb-data
      volumes:
        - name: postdb-data
          persistentVolumeClaim:
            claimName: postdb-pvc