apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: user:latest
          ports:
            - containerPort: 8080