apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE_SERVICE_URL
              value: "http://message:8080"
            - name: POST_SERVICE_URL
              value: "http://post:8080"
            - name: USER_SERVICE_URL
              value: "http://user:8080"
