apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: message:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
