apiVersion: apps/v1
kind: Deployment
metadata:
  name: authdb
spec:
  selector:
    matchLabels:
      app: authdb
  template:
    metadata:
      labels:
        app: authdb
    spec:
      containers:
        - name: authdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "auth"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authdb-storage
      volumes:
        - name: authdb-storage
          persistentVolumeClaim:
            claimName: authdb-pvc
