apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdb
spec:
  selector:
    matchLabels:
      app: userdb
  template:
    metadata:
      labels:
        app: userdb
    spec:
      containers:
        - name: userdb
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_DB
              value: "user"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: userdb-storage
      volumes:
        - name: userdb-storage
          persistentVolumeClaim:
            claimName: userdb-pvc
